version: '3.9'

services:
  api:
    build: .
    container_name: blog-api
    restart: always
    ports:
      - "3000:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
      DATABASE_URL: postgres://postgres:postgres@db:5432/blogdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
